//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class IAvatar
{
	protected GameObject myObj;
	protected GameObject _body;
	public IAvatar ()
	{
	}

	public virtual void resetSkin(int skinID, int sex) {
		
	}

	public virtual GameObject body {
		get {return null;}
		set { _body = value; }
	}

	public void setParent(GameObject parent){
		myObj.transform.parent = parent.transform;
	}
}

