//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class RichAvatar : IAvatar
{
	private GameObject bodyLayer; //身体各层容器
	public RichAvatar ()
	{
		init();
	}
		
	private void init() {
		myObj = new GameObject("RichAvatar");
		bodyLayer = new GameObject("bodyLayer");
		bodyLayer.transform.parent = myObj.transform;
	}
	
	public void resetSkinByTexture(int skinID, int sex)
	{
		
	}

	override public void resetSkin(int skinID, int sex)
	{
		if(body == null){
			GameObject sour = Resources.LoadAssetAtPath("Assets/Standard Assets/Character Controllers/Sources/PrototypeCharacter/Constructor.FBX", typeof(GameObject)) as GameObject;
			body = GameObject.Instantiate(sour) as GameObject;
		}
		body.transform.parent = bodyLayer.transform;
	}

	override public GameObject body {
		get {return _body;}
		set { _body = value; }
	}
}

