//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public class MonsterBehaviour : IAvatarBehaviour
{
	public MonsterBehaviour ()
	{
	}

    override public void runToPoint(Vector3 pointAft)
    {
        point = pointAft;
        transform.LookAt(new Vector3(point.x, transform.position.y, point.z));
        SetGameAct(AvatarUtil.ACT_WALK);
    }

    void FixedUpdate()
    {
        switch (curAct)
        {
            case AvatarUtil.ACT_STAND:

                break;
            case AvatarUtil.ACT_WALK:
                Move(0.05f);
                break;
        }
    }
}

