//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace module.scene.manager{
    using System;
    using System.Collections.Generic;
    using module.scene.sceneUnit.avatar;
    public class SceneUnitMgr
    {
        public SceneUnitMgr()
        {
        }
        private static Dictionary<string, SceneUnit> _unitHash = new Dictionary<string, SceneUnit>(); //放所有单位
        private static Dictionary<string, SceneUnit> _monsterHash = new Dictionary<string, SceneUnit>(); //放怪物

        public static int monsterNUM;

        public static void addUnit(SceneUnit unit)
        {
            if (_unitHash.ContainsKey(unit.id.ToString()) == false)
            { //总字典
                _unitHash[unit.id.ToString()] = unit;
            }
            if (unit.sceneType == SceneUnitType.MONSTER_TYPE)
            { //怪物字典
                if (_monsterHash.ContainsKey(unit.id.ToString()) == false)
                {
                    _monsterHash[unit.id.ToString()] = unit;
                    monsterNUM += 1;
                }
            }
        }

        public static SceneUnit getUnit(double unit_id)
        {
			if (_unitHash.ContainsKey(unit_id.ToString()) == false)
			{
				return null;
			}
            return _unitHash[unit_id.ToString()];
        }

    }
}

