//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class InputConstant
{
	public InputConstant ()
	{
	}

	public const int MOUSE_CLICK_LEFT = 0;
	public const int MOUSE_CLICK_RIGHT = 1;
	public const int MOUSE_CLICK_MIDDLE = 2;

	public const string EVENT_MOUSE_DOWN_LEFT = "EVENT_MOUSE_DOWN_LEFT";
	public const string EVENT_MOUSE_DOWN_RIGHT = "EVENT_MOUSE_DOWN_RIGHT";
	public const string EVENT_MOUSE_DOWN_MIDDLE = "EVENT_MOUSE_DOWN_MIDDLE";

}

