//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class SceneUnitType
{
	public SceneUnitType ()
	{
	}

	public const int ROLE_TYPE = 1;
	public const int MONSTER_TYPE = 2;
}
