//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace module.scene.sceneUnit.avatar{
    using System;
    using UnityEngine;
    public class Monster : SceneUnit
    {
        public Monster()
        {
			init();
        }

		override protected void init(){
			myObj.name = "Monster";
			avatar = new RichAvatar();
			avatar.setParent(myObj);
			sceneType = SceneUnitType.MONSTER_TYPE;
		}

        override public void reset(object value = null)
        {
            initBody();
        }

        private void initBody()
        {
			avatar.resetSkin(0,0);
            //body.AddComponent<CapsuleCollider>();
            //CapsuleCollider cap = body.GetComponent<CapsuleCollider>();
            //cap.radius = 10;
            behaviour = avatar.body.AddComponent("MonsterBehaviour") as IAvatarBehaviour;
            behaviour.unitID = id;

            collider = avatar.body.AddComponent<MeshCollider>();
        }
    }
}
