//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace module.scene.sceneUnit.avatar{
    using System;
    using UnityEngine;
	public class SceneUnit
    {
        public double id;
        public int sceneType;
		public bool isInit;
        protected int _status;

		protected GameObject myObj;
        protected IAvatar avatar;
        protected IAvatarBehaviour behaviour;
        protected MeshCollider collider;
        public SceneUnit()
        {
			myObj = new GameObject("SceneUnit");
        }

		protected virtual void init(){
			
		}

        public int status {
            get { return _status; }
			set {_status = value;}
		}

        public virtual void play(string act, string dir = null)
        {
            avatar.body.animation.Play();
        }

        public virtual void reset(object value = null)
        {

        }

        public virtual void resetPos(Vector3 pos)
        {
			pos.y = 1;
			myObj.transform.position = pos;
        }

        public virtual void resetSkin(int skinID, int sex)
        {

        }

		public void setParent(GameObject parent){
			myObj.transform.parent = parent.transform;
		}

        public void remove() {
            GameObject.Destroy(myObj);
        }
    }

}
